"""
Contains definitions for Lego Spike APIs so they can be used in the editor for
autocomplete and call tips.

Copyright (c) 2015-2019 Nicholas H.Tollervey and others (see the AUTHORS file).

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""


LEGO_APIS = [
    _("hub.BT_VCP.any \nAn undocumented part of the Lego API."),
    _("hub.BT_VCP.callback \nAn undocumented part of the Lego API."),
    _("hub.BT_VCP.close \nAn undocumented part of the Lego API."),
    _("hub.BT_VCP.isconnected \nAn undocumented part of the Lego API."),
    _("hub.BT_VCP.read \nAn undocumented part of the Lego API."),
    _("hub.BT_VCP.readinto \nAn undocumented part of the Lego API."),
    _("hub.BT_VCP.readline \nAn undocumented part of the Lego API."),
    _("hub.BT_VCP.readlines \nAn undocumented part of the Lego API."),
    _("hub.BT_VCP.recv \nAn undocumented part of the Lego API."),
    _("hub.BT_VCP.send \nAn undocumented part of the Lego API."),
    _("hub.BT_VCP.setinterrupt \nAn undocumented part of the Lego API."),
    _("hub.BT_VCP.write \nAn undocumented part of the Lego API."),
    _("hub.Image.ALL_ARROWS \nAn undocumented part of the Lego API."),
    _("hub.Image.ALL_CLOCKS \nAn undocumented part of the Lego API."),
    _("hub.Image.ANGRY \nAn undocumented part of the Lego API."),
    _("hub.Image.ARROW_E \nAn undocumented part of the Lego API."),
    _("hub.Image.ARROW_N \nAn undocumented part of the Lego API."),
    _("hub.Image.ARROW_NE \nAn undocumented part of the Lego API."),
    _("hub.Image.ARROW_NW \nAn undocumented part of the Lego API."),
    _("hub.Image.ARROW_S \nAn undocumented part of the Lego API."),
    _("hub.Image.ARROW_SE \nAn undocumented part of the Lego API."),
    _("hub.Image.ARROW_SW \nAn undocumented part of the Lego API."),
    _("hub.Image.ARROW_W \nAn undocumented part of the Lego API."),
    _("hub.Image.ASLEEP \nAn undocumented part of the Lego API."),
    _("hub.Image.BUTTERFLY \nAn undocumented part of the Lego API."),
    _("hub.Image.CHESSBOARD \nAn undocumented part of the Lego API."),
    _("hub.Image.CLOCK1 \nAn undocumented part of the Lego API."),
    _("hub.Image.CLOCK10 \nAn undocumented part of the Lego API."),
    _("hub.Image.CLOCK11 \nAn undocumented part of the Lego API."),
    _("hub.Image.CLOCK12 \nAn undocumented part of the Lego API."),
    _("hub.Image.CLOCK2 \nAn undocumented part of the Lego API."),
    _("hub.Image.CLOCK3 \nAn undocumented part of the Lego API."),
    _("hub.Image.CLOCK4 \nAn undocumented part of the Lego API."),
    _("hub.Image.CLOCK5 \nAn undocumented part of the Lego API."),
    _("hub.Image.CLOCK6 \nAn undocumented part of the Lego API."),
    _("hub.Image.CLOCK7 \nAn undocumented part of the Lego API."),
    _("hub.Image.CLOCK8 \nAn undocumented part of the Lego API."),
    _("hub.Image.CLOCK9 \nAn undocumented part of the Lego API."),
    _("hub.Image.CONFUSED \nAn undocumented part of the Lego API."),
    _("hub.Image.COW \nAn undocumented part of the Lego API."),
    _("hub.Image.DIAMOND \nAn undocumented part of the Lego API."),
    _("hub.Image.DIAMOND_SMALL \nAn undocumented part of the Lego API."),
    _("hub.Image.DUCK \nAn undocumented part of the Lego API."),
    _("hub.Image.FABULOUS \nAn undocumented part of the Lego API."),
    _("hub.Image.GHOST \nAn undocumented part of the Lego API."),
    _("hub.Image.GIRAFFE \nAn undocumented part of the Lego API."),
    _("hub.Image.HAPPY \nAn undocumented part of the Lego API."),
    _("hub.Image.HEART \nAn undocumented part of the Lego API."),
    _("hub.Image.HEART_SMALL \nAn undocumented part of the Lego API."),
    _("hub.Image.HOUSE \nAn undocumented part of the Lego API."),
    _("hub.Image.MEH \nAn undocumented part of the Lego API."),
    _("hub.Image.MUSIC_CROTCHET \nAn undocumented part of the Lego API."),
    _("hub.Image.MUSIC_QUAVER \nAn undocumented part of the Lego API."),
    _("hub.Image.MUSIC_QUAVERS \nAn undocumented part of the Lego API."),
    _("hub.Image.NO \nAn undocumented part of the Lego API."),
    _("hub.Image.PACMAN \nAn undocumented part of the Lego API."),
    _("hub.Image.PITCHFORK \nAn undocumented part of the Lego API."),
    _("hub.Image.RABBIT \nAn undocumented part of the Lego API."),
    _("hub.Image.ROLLERSKATE \nAn undocumented part of the Lego API."),
    _("hub.Image.SAD \nAn undocumented part of the Lego API."),
    _("hub.Image.SILLY \nAn undocumented part of the Lego API."),
    _("hub.Image.SKULL \nAn undocumented part of the Lego API."),
    _("hub.Image.SMILE \nAn undocumented part of the Lego API."),
    _("hub.Image.SNAKE \nAn undocumented part of the Lego API."),
    _("hub.Image.SQUARE \nAn undocumented part of the Lego API."),
    _("hub.Image.SQUARE_SMALL \nAn undocumented part of the Lego API."),
    _("hub.Image.STICKFIGURE \nAn undocumented part of the Lego API."),
    _("hub.Image.SURPRISED \nAn undocumented part of the Lego API."),
    _("hub.Image.SWORD \nAn undocumented part of the Lego API."),
    _("hub.Image.TARGET \nAn undocumented part of the Lego API."),
    _("hub.Image.TORTOISE \nAn undocumented part of the Lego API."),
    _("hub.Image.TRIANGLE \nAn undocumented part of the Lego API."),
    _("hub.Image.TRIANGLE_LEFT \nAn undocumented part of the Lego API."),
    _("hub.Image.TSHIRT \nAn undocumented part of the Lego API."),
    _("hub.Image.UMBRELLA \nAn undocumented part of the Lego API."),
    _("hub.Image.XMAS \nAn undocumented part of the Lego API."),
    _("hub.Image.YES \nAn undocumented part of the Lego API."),
    _("hub.Image.get_pixel \nAn undocumented part of the Lego API."),
    _("hub.Image.height \nAn undocumented part of the Lego API."),
    _("hub.Image.set_pixel \nAn undocumented part of the Lego API."),
    _("hub.Image.shift_down \nAn undocumented part of the Lego API."),
    _("hub.Image.shift_left \nAn undocumented part of the Lego API."),
    _("hub.Image.shift_right \nAn undocumented part of the Lego API."),
    _("hub.Image.shift_up \nAn undocumented part of the Lego API."),
    _("hub.Image.width \nAn undocumented part of the Lego API."),
    _("hub.USB_VCP.any \nAn undocumented part of the Lego API."),
    _("hub.USB_VCP.callback \nAn undocumented part of the Lego API."),
    _("hub.USB_VCP.close \nAn undocumented part of the Lego API."),
    _("hub.USB_VCP.isconnected \nAn undocumented part of the Lego API."),
    _("hub.USB_VCP.read \nAn undocumented part of the Lego API."),
    _("hub.USB_VCP.readinto \nAn undocumented part of the Lego API."),
    _("hub.USB_VCP.readline \nAn undocumented part of the Lego API."),
    _("hub.USB_VCP.readlines \nAn undocumented part of the Lego API."),
    _("hub.USB_VCP.recv \nAn undocumented part of the Lego API."),
    _("hub.USB_VCP.send \nAn undocumented part of the Lego API."),
    _("hub.USB_VCP.setinterrupt \nAn undocumented part of the Lego API."),
    _("hub.USB_VCP.write \nAn undocumented part of the Lego API."),
    _("hub.battery.BATTERY_BAD_BATTERY \nAn undocumented part of the Lego API."),
    _("hub.battery.BATTERY_HUB_TEMPERATURE_CRITICAL_OUT_OF_RANGE \nAn undocumented part of the Lego API."),
    _("hub.battery.BATTERY_NO_ERROR \nAn undocumented part of the Lego API."),
    _("hub.battery.BATTERY_TEMPERATURE_OUT_OF_RANGE \nAn undocumented part of the Lego API."),
    _("hub.battery.BATTERY_TEMPERATURE_SENSOR_FAIL \nAn undocumented part of the Lego API."),
    _("hub.battery.BATTERY_VOLTAGE_TOO_LOW \nAn undocumented part of the Lego API."),
    _("hub.battery.CHARGER_STATE_CHARGING_COMPLETED \nAn undocumented part of the Lego API."),
    _("hub.battery.CHARGER_STATE_CHARGING_ONGOING \nAn undocumented part of the Lego API."),
    _("hub.battery.CHARGER_STATE_DISCHARGING \nAn undocumented part of the Lego API."),
    _("hub.battery.CHARGER_STATE_FAIL \nAn undocumented part of the Lego API."),
    _("hub.battery.USB_CH_PORT_CDP \nAn undocumented part of the Lego API."),
    _("hub.battery.USB_CH_PORT_DCP \nAn undocumented part of the Lego API."),
    _("hub.battery.USB_CH_PORT_NONE \nAn undocumented part of the Lego API."),
    _("hub.battery.USB_CH_PORT_SDP \nAn undocumented part of the Lego API."),
    _("hub.battery.capacity_left \nAn undocumented part of the Lego API."),
    _("hub.battery.charger_detect \nAn undocumented part of the Lego API."),
    _("hub.battery.current \nAn undocumented part of the Lego API."),
    _("hub.battery.info \nAn undocumented part of the Lego API."),
    _("hub.battery.temperature \nAn undocumented part of the Lego API."),
    _("hub.battery.voltage \nAn undocumented part of the Lego API."),
    _("hub.ble.callback \nAn undocumented part of the Lego API."),
    _("hub.ble.connect \nAn undocumented part of the Lego API."),
    _("hub.ble.mac \nAn undocumented part of the Lego API."),
    _("hub.ble.rssi \nAn undocumented part of the Lego API."),
    _("hub.ble.scan \nAn undocumented part of the Lego API."),
    _("hub.ble.scan_result \nAn undocumented part of the Lego API."),
    _("hub.bluetooth.discoverable \nAn undocumented part of the Lego API."),
    _("hub.bluetooth.info \nAn undocumented part of the Lego API."),
    _("hub.button.center \nAn undocumented part of the Lego API."),
    _("hub.button.connect \nAn undocumented part of the Lego API."),
    _("hub.button.left \nAn undocumented part of the Lego API."),
    _("hub.button.right \nAn undocumented part of the Lego API."),
    _("hub.display.callback \nAn undocumented part of the Lego API."),
    _("hub.display.clear \nAn undocumented part of the Lego API."),
    _("hub.display.get_pixel \nAn undocumented part of the Lego API."),
    _("hub.display.rotation \nAn undocumented part of the Lego API."),
    _("hub.display.set_pixel \nAn undocumented part of the Lego API."),
    _("hub.display.show \nAn undocumented part of the Lego API."),
    _("hub.info \nAn undocumented part of the Lego API."),
    _("hub.led \nAn undocumented part of the Lego API."),
    _("hub.motion.BACK \nAn undocumented part of the Lego API."),
    _("hub.motion.DOUBLETAPPED \nAn undocumented part of the Lego API."),
    _("hub.motion.DOWN \nAn undocumented part of the Lego API."),
    _("hub.motion.FREEFALL \nAn undocumented part of the Lego API."),
    _("hub.motion.FRONT \nAn undocumented part of the Lego API."),
    _("hub.motion.LEFTSIDE \nAn undocumented part of the Lego API."),
    _("hub.motion.NONE \nAn undocumented part of the Lego API."),
    _("hub.motion.RIGHTSIDE \nAn undocumented part of the Lego API."),
    _("hub.motion.SHAKE \nAn undocumented part of the Lego API."),
    _("hub.motion.TAPPED \nAn undocumented part of the Lego API."),
    _("hub.motion.UP \nAn undocumented part of the Lego API."),
    _("hub.motion.accelerometer \nAn undocumented part of the Lego API."),
    _("hub.motion.callback \nAn undocumented part of the Lego API."),
    _("hub.motion.gesture \nAn undocumented part of the Lego API."),
    _("hub.motion.gyroscope \nAn undocumented part of the Lego API."),
    _("hub.motion.orientation \nAn undocumented part of the Lego API."),
    _("hub.motion.position \nAn undocumented part of the Lego API."),
    _("hub.motion.was_gesture \nAn undocumented part of the Lego API."),
    _("hub.port.A \nAn undocumented part of the Lego API."),
    _("hub.port.ATTACHED \nAn undocumented part of the Lego API."),
    _("hub.port.B \nAn undocumented part of the Lego API."),
    _("hub.port.C \nAn undocumented part of the Lego API."),
    _("hub.port.D \nAn undocumented part of the Lego API."),
    _("hub.port.DETACHED \nAn undocumented part of the Lego API."),
    _("hub.port.E \nAn undocumented part of the Lego API."),
    _("hub.port.F \nAn undocumented part of the Lego API."),
    _("hub.power_off \nAn undocumented part of the Lego API."),
    _("hub.sound.SOUND_SAWTOOTH \nAn undocumented part of the Lego API."),
    _("hub.sound.SOUND_SIN \nAn undocumented part of the Lego API."),
    _("hub.sound.SOUND_SQUARE \nAn undocumented part of the Lego API."),
    _("hub.sound.SOUND_TRIANGLE \nAn undocumented part of the Lego API."),
    _("hub.sound.beep \nAn undocumented part of the Lego API."),
    _("hub.sound.callback \nAn undocumented part of the Lego API."),
    _("hub.sound.play \nAn undocumented part of the Lego API."),
    _("hub.sound.volume \nAn undocumented part of the Lego API."),
    _("hub.status \nAn undocumented part of the Lego API."),
    _("hub.supervision.info \nAn undocumented part of the Lego API."),
    _("hub.temperature \nAn undocumented part of the Lego API."),
]
